# Generated by Django 6.1.1 on 2026-09-27 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('channel', models.CharField(default='Unknown Artist', max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('duration_str', models.CharField(default='00:00', max_length=50)),
                ('audio_format', models.CharField(default='MP3', max_length=10)),
                ('quality', models.CharField(default='320 kbps', max_length=50)),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_size', models.CharField(default='0 MB', max_length=50)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Download Record',
                'verbose_name_plural': 'Download Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
