# Generated by Django 6.1.1 on 2026-09-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('audio_format', models.CharField(default='mp3', max_length=10)),
                ('quality', models.CharField(default='320', max_length=50)),
                ('status', models.CharField(default='starting', max_length=50)),
                ('progress', models.FloatField(default=0.0)),
                ('speed', models.CharField(default='0 MB/s', max_length=50)),
                ('size', models.CharField(default='0 MB', max_length=50)),
                ('eta', models.CharField(default='--:--', max_length=50)),
                ('message', models.CharField(default='Connecting to YouTube...', max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('duration_str', models.CharField(blank=True, max_length=50, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
